#!/bin/bash

# 脚本说明：拉取origin/master的文件到本地，然后上传操作日志。
echo "\$0:$0"
echo "\$1:$1"
targetDir=$1

shellDir=$(dirname $0)
cd "$shellDir"
sh .inner_tools/git_pull $targetDir >> syn.log 2>&1

cd "$shellDir"
sh .inner_tools/upload_log $targetDir
